### ISSUE TITLE
Fix splash screen

### ISSUE THREAD

**Issue by shankarpriyank** [shankarpriyank/DocDelivery#24]
The splash screen implementation right now is not working as intended, it would be really useful if it gets fixed!

**Comment by VSen910** [comment]
Hi! May I know what the issue exactly is?

**Comment by shankarpriyank** [comment]
Hi @VSen910, thanks for showing your interest, I have used the splash screen api which came in Android 12, have a look [here](https://github.com/shankarpriyank/DocDelivery/blob/master/app/src/main/java/com/priyank/drdelivery/MainActivity.kt#L27), but when I test the app on my device all I see is the standard white splash screen. I did not really investigate what is the issue, but a feeling it either has something to do with compatibility or the size of the icon used in the splash screen theme (most probably it's because of this), also we need to update that icon!

**Comment by shankarpriyank** [comment]
Also if you need any help setting up the project on your local machine do let me know!

**Comment by VSen910** [comment]
Which icon do we need to update?

**Comment by VSen910** [comment]
Also, I figured out that if you run the app from Android Studio, the splash screen doesn't show up anyway, whereas if you start it from the device itself it shows up (I had to change the themes in the android manifest). But the thing is this API wants an icon over there rather than a full-screen image, so its boundaries are limited to a circle and that's why that image is somehow fitted into that circular area for the icon in the splash screen

**Comment by shankarpriyank** [comment]
Oh, you are able to see the splash screen now? That's great I have this icon to use now
![DocDel logo](https://user-images.githubusercontent.com/75121767/196257027-9696078c-2cb0-426a-bdc6-aa990b286b6c.svg)

**Comment by shankarpriyank** [comment]
Can you upload a screen shot of how the splash screen is looking right now?

**Comment by VSen910** [comment]
![image](https://user-images.githubusercontent.com/104011412/196257331-5ac1602c-620c-4592-8140-1247cd00318e.png)

**Comment by shankarpriyank** [comment]
Oh, I guess you can just update the icon, and write "DocDelivery" in the bottom using the Splash Screen API, you can use this for [reference](https://medium.com/realm/explore-splashscreen-api-android-12-kotlin-7a8bf83b061a)

Also, can you please open a pr so that I can see the changes

**Comment by VSen910** [comment]
There is some issue I'm not able to commit my changes, it throws an error

**Comment by shankarpriyank** [comment]
It is most probably cause the file is not formatted properely.

try running this command in the root directory
`gradlew ktlintFormat`

**Comment by VSen910** [comment]
This too gave an error

**Comment by shankarpriyank** [comment]
Could you please send the error message? It's really hard to help without context.

**Comment by VSen910** [comment]
FAILURE: Build failed with an exception.

* Where:
Build file 'D:\AndroidProjects\DocDelivery\app\build.gradle' line: 2

* What went wrong:
An exception occurred applying plugin request [id: 'com.android.application']
> Failed to apply plugin 'com.android.internal.application'.
   > Android Gradle plugin requires Java 11 to run. You are currently using Java 1.8.
     You can try some of the following options:
       - changing the IDE settings.
       - changing the JAVA_HOME environment variable.
       - changing `org.gradle.java.home` in `gradle.properties`.


Throws the same error when trying to commit

**Comment by shankarpriyank** [comment]
Did you try changing your jdk version to 11?

**Comment by VSen910** [comment]
Its already on 11 in android studio

**Comment by shankarpriyank** [comment]
Are you still working on this @VSen910?

**Comment by shankarpriyank** [comment]
No worries, If you could just paste a snippet of the changes that you made in the manifest file to get the above screen, that would really help a lot.

Thanks again for taking out your time!

**Comment by VSen910** [comment]
Oh sorry, just saw your comment. Good to hear it's solved finally :)
