### ISSUE TITLE
Correct Spelling Mistake in the readme file

### ISSUE THREAD

**Issue by shankarpriyank** [shankarpriyank/DocDelivery#8]
There is a spelling mistake in the readme file please correct it

**Comment by Stubborn7756** [comment]
DocDelivery is package/delivery tracking app which aims to minimize the efforts of the user to track his/her packages/deliveries.

**Comment by wraith756** [comment]
DocDelivery is package/delivery tracking app which aims to minimize the efforts of the user to track his/her packages/deliveries.

**Comment by stroopstrata** [comment]
Doc Delivery is package/delivery tracking app which aims to minimize the efforts of the user to track his/her packages/deliveries.

**Comment by shankarpriyank** [comment]
Closing this now as the it's fixed now
