### ISSUE TITLE
Add screenshots of the login screen in the readme section

### ISSUE THREAD

**Issue by shankarpriyank** [shankarpriyank/DocDelivery#9]
Please add a few screenshots of the onboarding screen in readme

**Comment by shankarpriyank** [comment]
Sure, You can take some inspiration on how to add the screenshots from [this](https://github.com/JunkFood02/Seal)

**Comment by trishitchar** [comment]
But  you didn't provide the live url. 
Can you guide me please.

**Comment by shankarpriyank** [comment]
Please to some digging around @trishitchar , DocDelivery is an app not a website.
The  build workflow builds an apk and uploads it in the artifact's everytime a commit is pushed in the main branch.
You can install the app from there.
Or build the app on your local machine itself.

Also you won't be able to login right now using the apk from artifact's, but still you can take a screenshot or make a gif/video of the onboarding process

**Comment by Photon3009** [comment]
@shankarpriyank if this issue is not resolved yet, can you assign it to me ?

**Comment by shankarpriyank** [comment]
@Photon3009 I have assigned the issue to you please go ahead and raise a pr, also I would advise you to make a new section and place it just above the installation section.
Also is there a way to add videos/gifs which will play on loop automatically in the readme?

**Comment by Photon3009** [comment]
@shankarpriyank yes I have made a gif regarding this and added it to the readme section.
And also created a PR so you can review it.
